version: '3.8'

services:
  # Database
  postgres:
    image: postgres:15-alpine
    container_name: postgres_db
    environment:
      POSTGRES_USER: rivals_admin
      POSTGRES_PASSWORD: rivals_admin
      POSTGRES_DB: rivals_db
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - /usr/src/app/node_modules

  # Tracker server
  api:
    build:
      context: ./server
      dockerfile: Dockerfile
    container_name: tracker_server
    depends_on:
      - postgres
    ports:
      - '3000:3000'
    environment:
      DATABASE_URL: "postgresql://rivals_admin:rivals_admin@postgres:5432/rivals_db?schema=public"
    volumes:
      - ./server:/usr/src/app/server
      - /usr/src/app/server/node_modules # Prevents local modules from overriding container modules

volumes:
  postgres_data: